import { Deal } from "@/types";

export const MOCK_DEALS: Deal[] = [
  {
    id: "mock-1",
    firm_id: "mock-firm",
    company_name: "Nexus AI",
    one_liner: "AI-powered workflow automation for enterprise",
    stage: "first_meeting",
    source: "referral",
    sector: "Enterprise Software",
    sub_sector: "AI/ML",
    asking_valuation: 12000000,
    proposed_check: 2000000,
    round_size: 8000000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    firm_id: "mock-firm",
    company_name: "HealthBridge",
    one_liner: "Telehealth platform connecting patients with specialists",
    stage: "deep_dive",
    source: "inbound",
    sector: "Healthcare",
    sub_sector: "Digital Health",
    asking_valuation: 25000000,
    proposed_check: 3000000,
    round_size: 12000000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    firm_id: "mock-firm",
    company_name: "GreenGrid",
    one_liner: "Grid-scale battery storage for renewable energy",
    stage: "ic_review",
    source: "conference",
    sector: "Climate Tech",
    sub_sector: "Energy Storage",
    asking_valuation: 45000000,
    proposed_check: 5000000,
    round_size: 20000000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    firm_id: "mock-firm",
    company_name: "DataVault",
    one_liner: "Compliance-first data warehouse for regulated industries",
    stage: "screening",
    source: "outbound",
    sector: "Enterprise Software",
    sub_sector: "Data Infrastructure",
    asking_valuation: 18000000,
    proposed_check: 2500000,
    round_size: 10000000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-5",
    firm_id: "mock-firm",
    company_name: "FinServe",
    one_liner: "Embedded payments for B2B marketplaces",
    stage: "term_sheet",
    source: "portfolio_intro",
    sector: "Fintech",
    sub_sector: "Payments",
    asking_valuation: 35000000,
    proposed_check: 4000000,
    round_size: 15000000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-6",
    firm_id: "mock-firm",
    company_name: "FlowBase",
    one_liner: "No-code automation for ops teams",
    stage: "inbound",
    source: "inbound",
    sector: "Productivity",
    sub_sector: "Workflow",
    asking_valuation: 8000000,
    proposed_check: 1500000,
    round_size: 5000000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_DEALS_RESPONSE = {
  deals: MOCK_DEALS,
  total: MOCK_DEALS.length,
  page: 1,
  per_page: 200,
  total_pages: 1,
};
